In [22]:
hashtags = ['calenda', 'meloni', 'salvini', 'azione', 'terzopolo', 'letta',
           'partitodemocratico', 'renzi', '25settembre', 'elezioni2022_new', 'conte']

In [23]:
import networkx as nx
import pandas as pd
import numpy as np
import re

import os
import glob
# use glob to get all the csv files in the folder

path = os.getcwd()
csv_files = glob.glob(os.path.join(path, "*.csv"))

for f in csv_files:
      
    # read the csv file
    df = pd.read_csv(f)
      
    # print the location and filename
    print('Location:', f)
    print('File Name:', f.split("\\")[-1])
      
    # print the content
    print('Content:')
    display(df)
    print()

Location: C:\Users\Giova\OneDrive\Desktop\UNIPI\MAGISTRALE\Social Network Analysis\25settembre.csv
File Name: 25settembre.csv
Content:

,Unnamed: 0,id,conversation_id,created_at,date,time,timezone,user_id,username,name,...,geo,source,user_rt_id,user_rt,retweet_id,reply_to,retweet_date,translate,trans_src,trans_dest
0,0,1557515610048929793,1557515610048929792,2022-08-11 01:53:53 W. Europe Daylight Time,2022-08-11,01:53:53,200,973452510,villasantacomun,Comune di Villasanta,...,NaN,NaN,NaN,NaN,NaN,[],NaN,NaN,NaN,NaN
1,1,1557512505781620736,1557512505781620736,2022-08-11 01:41:33 W. Europe Daylight Time,2022-08-11,01:41:33,200,3072288777,davidemarcone_,Davide,...,NaN,NaN,NaN,NaN,NaN,[],NaN,NaN,NaN,NaN
2,2,1557511362506641409,1557346563948773376,2022-08-11 01:37:00 W. Europe Daylight Time,2022-08-11,01:37:00,200,707658874,demarchifra,Francesco Saverio,...,NaN,NaN,NaN,NaN,NaN,"[{'screen_name': 'Laura_Virgy', 'name': 'Laura...",NaN,NaN,NaN,NaN
3,3,1557511199100649472,1557398923765026816,2022-08-11 01:36:21 W. Europe Daylight Time,2022-08-11,01:36:21,200,1304915840161263626,cavalierebianc5,cavalierebianco,...,NaN,NaN,NaN,NaN,NaN,"[{'screen_name': 'ascochita', 'name': 'Alessan...",NaN,NaN,NaN,NaN
4,4,1557510426375626755,1557510426375626752,2022-08-11 01:33:17 W. Europe Daylight Time,2022-08-11,01:33:17,200,983067694638317571,gabriflo1,Gabriele Floris 🇪🇺🇮🇹,...,NaN,NaN,NaN,NaN,NaN,[],NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1124,15,1575223973595447310,1575223973595447296,2022-09-28 22:40:36 W. Europe Daylight Time,2022-09-28,22:40:36,200,849936108850905089,runningsprtnews,RunningSportNews,...,NaN,NaN,NaN,NaN,NaN,[],NaN,NaN,NaN,NaN
1125,16,1575222596932714496,1575222596932714496,2022-09-28 22:35:07 W. Europe Daylight Time,2022-09-28,22:35:07,200,317671787,infoitinterno,informazione interno,...,NaN,NaN,NaN,NaN,NaN,[],NaN,NaN,NaN,NaN
1126,17,1575221471290740736,1568323132779266048,2022-09-28 22:30:39 W. Europe Daylight Time,2022-09-28,22:30:39,200,988343473,editta_fazzi,Editta Tardelli,...,NaN,NaN,NaN,NaN,NaN,"[{'screen_name': 'clementecuoghi', 'name': 'cl...",NaN,NaN,NaN,NaN
1127,18,1575218854992572424,1575210960826007552,2022-09-28 22:20:15 W. Europe Daylight Time,2022-09-28,22:20:15,200,1115345176912855042,paoloburatti3,paoloburatti,...,NaN,NaN,NaN,NaN,NaN,"[{'screen_name': 'Moreno01720679', 'name': 'Mo...",NaN,NaN,NaN,NaN
1128,19,1575217455412432896,1575002375080722432,2022-09-28 22:14:42 W. Europe Daylight Time,2022-09-28,22:14:42,200,3426991144,kittesencul,La nonna (ex) Stagista,...,NaN,NaN,NaN,NaN,NaN,"[{'screen_name': 'fgavazzoni', 'name': 'Federi...",NaN,NaN,NaN,NaN

Location: C:\Users\Giova\OneDrive\Desktop\UNIPI\MAGISTRALE\Social Network Analysis\azione.csv
File Name: azione.csv
Content:

,Unnamed: 0,id,conversation_id,created_at,date,time,timezone,user_id,username,name,...,geo,source,user_rt_id,user_rt,retweet_id,reply_to,retweet_date,translate,trans_src,trans_dest
0,1,1558241263912206342,1558110065424482304,2022-08-13 01:57:22 W. Europe Daylight Time,2022-08-13,01:57:22,200,371781632,raffaelepizzati,Raffaele Pizzati,...,NaN,NaN,NaN,NaN,NaN,"[{'screen_name': 'renzo_roso', 'name': 'renzo ...",NaN,NaN,NaN,NaN
1,2,1558241129304395776,1557694811473338368,2022-08-13 01:56:50 W. Europe Daylight Time,2022-08-13,01:56:50,200,1118621501530476544,polemicarc,Architetto Polemico,...,NaN,NaN,NaN,NaN,NaN,"[{'screen_name': 'MadameA02', 'name': 'Madame ...",NaN,NaN,NaN,NaN
2,3,1558240658799923200,1558062018636169216,2022-08-13 01:54:58 W. Europe Daylight Time,2022-08-13,01:54:58,200,1267520722953437184,lukepazz,Lukepazz🇸🇩,...,NaN,NaN,NaN,NaN,NaN,"[{'screen_name': 'msgelmini', 'name': 'Mariast...",NaN,NaN,NaN,NaN
3,4,1558240004081471489,1558081217177714688,2022-08-13 01:52:22 W. Europe Daylight Time,2022-08-13,01:52:22,200,417250729,sergio_dib,Sergio Di Benedetto,...,NaN,NaN,NaN,NaN,NaN,"[{'screen_name': 'gennaromigliore', 'name': 'G...",NaN,NaN,NaN,NaN
4,5,1558239709821865984,1558062018636169216,2022-08-13 01:51:12 W. Europe Daylight Time,2022-08-13,01:51:12,200,1500033310449446915,giuse_salerno,Giuseppe Salerno,...,NaN,NaN,NaN,NaN,NaN,"[{'screen_name': 'msgelmini', 'name': 'Mariast...",NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3171,1513,1575640891574071296,1575615534896279552,2022-09-30 02:17:17 W. Europe Daylight Time,2022-09-30,02:17:17,200,541161137,parkeggio,giovanni 🇮🇹,...,NaN,NaN,NaN,NaN,NaN,"[{'screen_name': 'borghi_claudio', 'name': 'Cl...",NaN,NaN,NaN,NaN
3172,1514,1575640319843979264,1575222766181097472,2022-09-30 02:15:00 W. Europe Daylight Time,2022-09-30,02:15:00,200,1250430220043038720,arcp_it,alberto,...,NaN,NaN,NaN,NaN,NaN,"[{'screen_name': 'CollotMarta', 'name': 'Marta...",NaN,NaN,NaN,NaN
3173,1515,1575639512012947456,1575580409295147008,2022-09-30 02:11:48 W. Europe Daylight Time,2022-09-30,02:11:48,200,2735617614,micia274,micia,...,NaN,NaN,NaN,NaN,NaN,"[{'screen_name': 'christianazione', 'name': 'C...",NaN,NaN,NaN,NaN
3174,1516,1575638034095034370,1575580409295147008,2022-09-30 02:05:55 W. Europe Daylight Time,2022-09-30,02:05:55,200,2735617614,micia274,micia,...,NaN,NaN,NaN,NaN,NaN,"[{'screen_name': 'AvvOrunesu', 'name': 'Luca O...",NaN,NaN,NaN,NaN
3175,1517,1575637437069463553,1575637437069463552,2022-09-30 02:03:33 W. Europe Daylight Time,2022-09-30,02:03:33,200,1366731780393496580,alex50551675,Alex,...,NaN,NaN,NaN,NaN,NaN,[],NaN,NaN,NaN,NaN

Location: C:\Users\Giova\OneDrive\Desktop\UNIPI\MAGISTRALE\Social Network Analysis\calenda.csv
File Name: calenda.csv
Content:

,Unnamed: 0,id,conversation_id,created_at,date,time,timezone,user_id,username,name,...,geo,source,user_rt_id,user_rt,retweet_id,reply_to,retweet_date,translate,trans_src,trans_dest
0,0,1557879323104874496,1557808175339945984,2022-08-12 01:59:09 W. Europe Daylight Time,2022-08-12,01:59:09,200,2609504528,womanwithpen,Elisa P. Barrett,...,NaN,NaN,NaN,NaN,NaN,"[{'screen_name': 'frances90833421', 'name': 'f...",NaN,NaN,NaN,NaN
1,1,1557879237108965377,1557879237108965376,2022-08-12 01:58:48 W. Europe Daylight Time,2022-08-12,01:58:48,200,1018886994435493888,davidecrusader,Davide✝️Crusader🇮🇹♦️♦️♦️♦️🃏,...,NaN,NaN,NaN,NaN,NaN,[],NaN,NaN,NaN,NaN
2,2,1557878657854672896,1557878657854672896,2022-08-12 01:56:30 W. Europe Daylight Time,2022-08-12,01:56:30,200,420351046,sole24ore,IlSole24ORE,...,NaN,NaN,NaN,NaN,NaN,[],NaN,NaN,NaN,NaN
3,4,1557878319189835777,1557446894514839552,2022-08-12 01:55:09 W. Europe Daylight Time,2022-08-12,01:55:09,200,3085023297,riccard64053720,Riccardo,...,NaN,NaN,NaN,NaN,NaN,"[{'screen_name': 'elevisconti', 'name': 'Elena...",NaN,NaN,NaN,NaN
4,5,1557877915584438279,1557785829971566592,2022-08-12 01:53:33 W. Europe Daylight Time,2022-08-12,01:53:33,200,3957668361,enrigoletto,enrigoletto,...,NaN,NaN,NaN,NaN,NaN,"[{'screen_name': 'conteDartagnan', 'name': ""Ch...",NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4301,1934,1575650892619329536,1575396230083092480,2022-09-30 02:57:01 W. Europe Daylight Time,2022-09-30,02:57:01,200,1458156664939483137,cristianadigra2,Cristiana Di Grazia,...,NaN,NaN,NaN,NaN,NaN,"[{'screen_name': 'LuigiPelliciol3', 'name': 'L...",NaN,NaN,NaN,NaN
4302,1936,1575643016584654848,1574513439946735616,2022-09-30 02:25:43 W. Europe Daylight Time,2022-09-30,02:25:43,200,1573965522936406016,manugiudy1,Manugiudy1,...,NaN,NaN,NaN,NaN,NaN,"[{'screen_name': 'zarzingale', 'name': 'Antoni...",NaN,NaN,NaN,NaN
4303,1937,1575642007074091008,1575566093694869504,2022-09-30 02:21:43 W. Europe Daylight Time,2022-09-30,02:21:43,200,1553667629608570880,frances22449915,Francesca Martelli#iovotoitaliaviva,...,NaN,NaN,NaN,NaN,NaN,"[{'screen_name': 'EmiliaBalestri1', 'name': 'E...",NaN,NaN,NaN,NaN
4304,1939,1575640572953391104,1575640572953391104,2022-09-30 02:16:01 W. Europe Daylight Time,2022-09-30,02:16:01,200,1427559614833385473,poghos2003,Poghos🇮🇹🇻🇦🇪🇸🇦🇲,...,NaN,NaN,NaN,NaN,NaN,[],NaN,NaN,NaN,NaN
4305,1940,1575640297232510976,1575580409295147008,2022-09-30 02:14:55 W. Europe Daylight Time,2022-09-30,02:14:55,200,2735617614,micia274,micia,...,NaN,NaN,NaN,NaN,NaN,"[{'screen_name': 'ArtegianiNicola', 'name': 'N...",NaN,NaN,NaN,NaN

Location: C:\Users\Giova\OneDrive\Desktop\UNIPI\MAGISTRALE\Social Network Analysis\conte.csv
File Name: conte.csv
Content:

,Unnamed: 0,id,conversation_id,created_at,date,time,timezone,user_id,username,name,...,geo,source,user_rt_id,user_rt,retweet_id,reply_to,retweet_date,translate,trans_src,trans_dest
0,1,1558604192847204355,1558326763037401088,2022-08-14 01:59:31 W. Europe Daylight Time,2022-08-14,01:59:31,200,2236327369,stefaniaespos19,Stefania esposito,...,NaN,NaN,NaN,NaN,NaN,"[{'screen_name': 'SkyTG24', 'name': 'Sky tg24'...",NaN,NaN,NaN,NaN
1,23,1558603466624360448,1558601033315753984,2022-08-14 01:56:38 W. Europe Daylight Time,2022-08-14,01:56:38,200,51757652,nonleggerlo,nonleggerlo,...,NaN,NaN,NaN,NaN,NaN,"[{'screen_name': 'AndreaZani7', 'name': 'Andre...",NaN,NaN,NaN,NaN
2,26,1558603359468326914,1558430670921248768,2022-08-14 01:56:13 W. Europe Daylight Time,2022-08-14,01:56:13,200,1250735310213910529,scienzan,Scienza dei Numeri,...,NaN,NaN,NaN,NaN,NaN,"[{'screen_name': 'Mov5Stelle', 'name': 'MoVime...",NaN,NaN,NaN,NaN
3,34,1558602830520504320,1558602830520504320,2022-08-14 01:54:06 W. Europe Daylight Time,2022-08-14,01:54:06,200,428447147,tarabbo,alba tarabbo,...,NaN,NaN,NaN,NaN,NaN,[],NaN,NaN,NaN,NaN
4,4,1558966632730566656,1558757293122113536,2022-08-15 01:59:44 W. Europe Daylight Time,2022-08-15,01:59:44,200,1519076522186924032,vera87072826,Unknow171128new,...,NaN,NaN,NaN,NaN,NaN,"[{'screen_name': 'Pinomini57', 'name': 'Jihadi...",NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
146,20,1575998291103342592,1575998291103342592,2022-10-01 01:57:27 W. Europe Daylight Time,2022-10-01,01:57:27,200,1404121928571490305,mattiamattiaaa,Mattia Pellegrino,...,NaN,NaN,NaN,NaN,NaN,[],NaN,NaN,NaN,NaN
147,22,1575997948873572353,1575900158705176576,2022-10-01 01:56:06 W. Europe Daylight Time,2022-10-01,01:56:06,200,72659857,federicafa,federica,...,NaN,NaN,NaN,NaN,NaN,"[{'screen_name': 'speziata', 'name': 'GingeR',...",NaN,NaN,NaN,NaN
148,26,1575997695713386497,1575858169594593280,2022-10-01 01:55:05 W. Europe Daylight Time,2022-10-01,01:55:05,200,371781632,raffaelepizzati,Raffaele Pizzati,...,NaN,NaN,NaN,NaN,NaN,"[{'screen_name': 'Favollo2', 'name': ""Gimmoris...",NaN,NaN,NaN,NaN
149,31,1575997375318933506,1575751019883110400,2022-10-01 01:53:49 W. Europe Daylight Time,2022-10-01,01:53:49,200,1196890842985893888,jurodivye,Jurodivye,...,NaN,NaN,NaN,NaN,NaN,"[{'screen_name': 'marcopalears', 'name': '𝙼𝙰𝚁𝙲...",NaN,NaN,NaN,NaN
150,33,1575997215121604608,1575798777788743680,2022-10-01 01:53:11 W. Europe Daylight Time,2022-10-01,01:53:11,200,2999709473,con_la_j,Tanja,...,NaN,NaN,NaN,NaN,NaN,"[{'screen_name': 'Viv_Dany', 'name': 'Daniela ...",NaN,NaN,NaN,NaN

Location: C:\Users\Giova\OneDrive\Desktop\UNIPI\MAGISTRALE\Social Network Analysis\df_tutti.csv
File Name: df_tutti.csv
Content:

,Unnamed: 0,Unnamed: 0.1,date,user_id,username,name,tweet,mentions,replies_count,retweets_count,likes_count,hashtags,retweet,geo,retweet_id,reply_to
0,0,1,2022-08-24,484337760,francoinzirillo,francesco inzirillo,#ElezioniPolitiche22 Manifesto convocazione ...,[],0,0,0,"['elezionipolitiche22', 'comizielettorali', 'v...",False,NaN,NaN,[]
1,1,2,2022-08-23,376610294,isabellarauti,Isabella Rauti,"Fratelli d'Italia, ecco tutti i candidati in L...","[{'screen_name': 'fratelliditalia', 'name': ""f...",1,3,15,"['elezionipolitiche', 'pronti', 'fdi']",False,NaN,NaN,[]
2,2,3,2022-08-23,50355977,fralauricella,Francesco Lauricella,Duro attacco di Daniela #Santanche a Giorgia #...,[],0,1,1,"['santanche', 'meloni', 'devianze', 'elezionip...",False,NaN,NaN,[]
3,3,5,2022-08-23,50355977,fralauricella,Francesco Lauricella,@SimoPillon @sbonaccini @MonicaCirinna #Salvin...,[],0,2,2,"['salvini', 'berlusconi', 'meloni', 'morisi', ...",False,NaN,NaN,"[{'screen_name': 'SimoPillon', 'name': 'Simone..."
4,4,6,2022-08-23,1506902792224530432,leone_ottanta,Leone80_Fede🤍👨‍👩‍👧‍👦🤍,@lauraboldrini Crederó alla sua predica e a qu...,"[{'screen_name': 'pdnetwork', 'name': 'partito...",0,0,1,"['melonivergogna', 'stupro', 'elezionipolitich...",False,NaN,NaN,"[{'screen_name': 'lauraboldrini', 'name': 'Lau..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2428,809,34,2022-09-25,2907503735,lacavaz,Emanuela Cavazzini 🇪🇺🇺🇦🏳️‍🌈,momenti tragicomici che hanno coinvolto i prot...,[],0,0,0,['elezioni2022'],False,NaN,NaN,[]
2429,810,35,2022-09-25,551188862,phdmatteo,Matteo_T,In attesa (anche) del voto di domani. Nonostan...,[],0,0,3,"['pavese', 'elezionipolitiche2022', 'elezionip...",False,NaN,NaN,[]
2430,811,36,2022-09-25,747187674,andreamaggio76,Andrea Maggio,#ElezioniPolitiche2022 #elezioni2022 #Elezioni...,[],0,0,0,"['elezionipolitiche2022', 'elezioni2022', 'ele...",False,NaN,NaN,[]
2431,812,37,2022-09-25,1142782223193653249,leonessa1864,☀️❤🌟🌟🌟Anny🌟🌟❤☀️,"Lunedì, se va come penso, dobbiamo mandare in ...",[],0,0,2,"['grazieatuttiicazzari', 'dallapartegiusta', '...",False,NaN,NaN,[]
2432,813,38,2022-09-25,1337861522274521090,realdonatotramp,DONATO Z TRUMP 🇺🇸🇮🇹🇷🇺,@Sissijj14 @Guissi36575315 Dove sta il #pd non...,[],0,0,2,"['pd', 'elezionipolitiche2022', 'elezioni2022']",False,NaN,NaN,"[{'screen_name': 'Sissijj14', 'name': '🇷🇺 αмєℓ..."

Location: C:\Users\Giova\OneDrive\Desktop\UNIPI\MAGISTRALE\Social Network Analysis\elezioni2022_new.csv
File Name: elezioni2022_new.csv
Content:

,Unnamed: 0,id,conversation_id,created_at,date,time,timezone,user_id,username,name,...,geo,source,user_rt_id,user_rt,retweet_id,reply_to,retweet_date,translate,trans_src,trans_dest
0,0,1563673082002153472,1563673082002153472,2022-08-28 01:41:29 W. Europe Daylight Time,2022-08-28,01:41:29,200,958522192857251841,careitaly,Nicola Carè,...,NaN,NaN,NaN,NaN,NaN,[],NaN,NaN,NaN,NaN
1,3,1563662585370738688,1563662585370738688,2022-08-28 00:59:46 W. Europe Daylight Time,2022-08-28,00:59:46,200,1001505012235763713,comitatopiero,Comitato Firenze Possibile Piero Calamandrei,...,NaN,NaN,NaN,NaN,NaN,[],NaN,NaN,NaN,NaN
2,4,1563660242222624769,1563660242222624768,2022-08-28 00:50:27 W. Europe Daylight Time,2022-08-28,00:50:27,200,1198355954678616064,maryilritorno,Maryilritorno 🏳️‍🌈,...,NaN,NaN,NaN,NaN,NaN,[],NaN,NaN,NaN,NaN
3,5,1563655195766435840,1563655195766435840,2022-08-28 00:30:24 W. Europe Daylight Time,2022-08-28,00:30:24,200,1188924175412551683,lcafuero,Luca Cafuero,...,NaN,NaN,NaN,NaN,NaN,[],NaN,NaN,NaN,NaN
4,6,1563650158868533250,1563650158868533248,2022-08-28 00:10:23 W. Europe Daylight Time,2022-08-28,00:10:23,200,454806737,valentasposato,valentinasposato,...,NaN,NaN,NaN,NaN,NaN,[],NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
809,34,1573796476328845313,1573796476328845312,2022-09-25 00:08:14 W. Europe Daylight Time,2022-09-25,00:08:14,200,2907503735,lacavaz,Emanuela Cavazzini 🇪🇺🇺🇦🏳️‍🌈,...,NaN,NaN,NaN,NaN,NaN,[],NaN,NaN,NaN,NaN
810,35,1573796250004111362,1573796250004111360,2022-09-25 00:07:20 W. Europe Daylight Time,2022-09-25,00:07:20,200,551188862,phdmatteo,Matteo_T,...,NaN,NaN,NaN,NaN,NaN,[],NaN,NaN,NaN,NaN
811,36,1573795792539860993,1573795792539860992,2022-09-25 00:05:31 W. Europe Daylight Time,2022-09-25,00:05:31,200,747187674,andreamaggio76,Andrea Maggio,...,NaN,NaN,NaN,NaN,NaN,[],NaN,NaN,NaN,NaN
812,37,1573795776567951367,1573795776567951360,2022-09-25 00:05:27 W. Europe Daylight Time,2022-09-25,00:05:27,200,1142782223193653249,leonessa1864,☀️❤🌟🌟🌟Anny🌟🌟❤☀️,...,NaN,NaN,NaN,NaN,NaN,[],NaN,NaN,NaN,NaN
813,38,1573795622116904960,1573783344634028032,2022-09-25 00:04:50 W. Europe Daylight Time,2022-09-25,00:04:50,200,1337861522274521090,realdonatotramp,DONATO Z TRUMP 🇺🇸🇮🇹🇷🇺,...,NaN,NaN,NaN,NaN,NaN,"[{'screen_name': 'Sissijj14', 'name': '🇷🇺 αмєℓ...",NaN,NaN,NaN,NaN

Location: C:\Users\Giova\OneDrive\Desktop\UNIPI\MAGISTRALE\Social Network Analysis\elezionipolitiche.csv
File Name: elezionipolitiche.csv
Content:

,Unnamed: 0,id,conversation_id,created_at,date,time,timezone,user_id,username,name,...,geo,source,user_rt_id,user_rt,retweet_id,reply_to,retweet_date,translate,trans_src,trans_dest
0,1,1562205451160281089,1562205451160281088,2022-08-24 00:29:38 W. Europe Daylight Time,2022-08-24,00:29:38,200,484337760,francoinzirillo,francesco inzirillo,...,NaN,NaN,NaN,NaN,NaN,[],NaN,NaN,NaN,NaN
1,2,1562196083152801793,1562196083152801792,2022-08-23 23:52:25 W. Europe Daylight Time,2022-08-23,23:52:25,200,376610294,isabellarauti,Isabella Rauti,...,NaN,NaN,NaN,NaN,NaN,[],NaN,NaN,NaN,NaN
2,3,1562193422358040579,1562193422358040576,2022-08-23 23:41:50 W. Europe Daylight Time,2022-08-23,23:41:50,200,50355977,fralauricella,Francesco Lauricella,...,NaN,NaN,NaN,NaN,NaN,[],NaN,NaN,NaN,NaN
3,5,1562191664239616000,1562062598962614272,2022-08-23 23:34:51 W. Europe Daylight Time,2022-08-23,23:34:51,200,50355977,fralauricella,Francesco Lauricella,...,NaN,NaN,NaN,NaN,NaN,"[{'screen_name': 'SimoPillon', 'name': 'Simone...",NaN,NaN,NaN,NaN
4,6,1562186680731422720,1562106991060852736,2022-08-23 23:15:03 W. Europe Daylight Time,2022-08-23,23:15:03,200,1506902792224530432,leone_ottanta,Leone80_Fede🤍👨‍👩‍👧‍👦🤍,...,NaN,NaN,NaN,NaN,NaN,"[{'screen_name': 'lauraboldrini', 'name': 'Lau...",NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
485,31,1573665050774102021,1573665050774102016,2022-09-24 15:26:00 W. Europe Daylight Time,2022-09-24,15:26:00,200,922868459972775937,gastroprotetto,gastroprotetto,...,NaN,NaN,NaN,NaN,NaN,[],NaN,NaN,NaN,NaN
486,32,1573664702193979396,1573664702193979392,2022-09-24 15:24:36 W. Europe Daylight Time,2022-09-24,15:24:36,200,1188121472054812672,duckpapero,Dr Duck Papero - Zerologo,...,NaN,NaN,NaN,NaN,NaN,[],NaN,NaN,NaN,NaN
487,33,1573664620547637248,1572857261953028096,2022-09-24 15:24:17 W. Europe Daylight Time,2022-09-24,15:24:17,200,1188121472054812672,duckpapero,Dr Duck Papero - Zerologo,...,NaN,NaN,NaN,NaN,NaN,"[{'screen_name': 'maddai_', 'name': 'Maddalena...",NaN,NaN,NaN,NaN
488,34,1573664038474727424,1573664038474727424,2022-09-24 15:21:58 W. Europe Daylight Time,2022-09-24,15:21:58,200,1552031693770457091,aletodaro03,Alessandro Todaro,...,NaN,NaN,NaN,NaN,NaN,[],NaN,NaN,NaN,NaN
489,35,1573663784526307329,1573663784526307328,2022-09-24 15:20:58 W. Europe Daylight Time,2022-09-24,15:20:58,200,197056224,annaquercia,ANNA QUERCIA autrice,...,NaN,NaN,NaN,NaN,NaN,[],NaN,NaN,NaN,NaN

Location: C:\Users\Giova\OneDrive\Desktop\UNIPI\MAGISTRALE\Social Network Analysis\letta.csv
File Name: letta.csv
Content:

,Unnamed: 0,id,conversation_id,created_at,date,time,timezone,user_id,username,name,...,geo,source,user_rt_id,user_rt,retweet_id,reply_to,retweet_date,translate,trans_src,trans_dest
0,0,1557517074804654084,1557362920182390784,2022-08-11 01:59:42 W. Europe Daylight Time,2022-08-11,01:59:42,200,1357811678113579010,pierluigidimat2,Pierluigi Di Matteo,...,NaN,NaN,NaN,NaN,NaN,"[{'screen_name': 'riotta', 'name': 'Gianni Rio...",NaN,NaN,NaN,NaN
1,1,1557516753340702721,1557516753340702720,2022-08-11 01:58:25 W. Europe Daylight Time,2022-08-11,01:58:25,200,1448502579613376520,ghinodiattacco,Ghino di Punta,...,NaN,NaN,NaN,NaN,NaN,[],NaN,NaN,NaN,NaN
2,2,1557516395172306948,1557516395172306944,2022-08-11 01:57:00 W. Europe Daylight Time,2022-08-11,01:57:00,200,231726084,zazoomblog,Zazoom Social News,...,NaN,NaN,NaN,NaN,NaN,[],NaN,NaN,NaN,NaN
3,3,1557516319096016897,1557392931727745024,2022-08-11 01:56:42 W. Europe Daylight Time,2022-08-11,01:56:42,200,1417215075190968324,prodepeppino,Anticorpo Democratico 🇮🇹 🇪🇺,...,NaN,NaN,NaN,NaN,NaN,"[{'screen_name': 'pinelliman', 'name': 'Emanue...",NaN,NaN,NaN,NaN
4,4,1557515160679579648,1557446894514839552,2022-08-11 01:52:06 W. Europe Daylight Time,2022-08-11,01:52:06,200,516542964,levobi,Leonardo Brancaccio 🇪🇺,...,NaN,NaN,NaN,NaN,NaN,"[{'screen_name': 'elevisconti', 'name': 'Elena...",NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1057,13,1575989338764185600,1575989338764185600,2022-10-01 01:21:53 W. Europe Daylight Time,2022-10-01,01:21:53,200,317737372,infoitcultura,informazione cultura,...,NaN,NaN,NaN,NaN,NaN,[],NaN,NaN,NaN,NaN
1058,15,1575988893324918786,1575988893324918784,2022-10-01 01:20:07 W. Europe Daylight Time,2022-10-01,01:20:07,200,78567974,tempoweb,IL TEMPO,...,NaN,NaN,NaN,NaN,NaN,[],NaN,NaN,NaN,NaN
1059,16,1575988027083862016,1575902720212754432,2022-10-01 01:16:40 W. Europe Daylight Time,2022-10-01,01:16:40,200,1519223905679990785,wazzacn,Wazza 🪖,...,NaN,NaN,NaN,NaN,NaN,"[{'screen_name': 'Nicola83203236', 'name': 'N'...",NaN,NaN,NaN,NaN
1060,17,1575987676859113472,1575833758158454784,2022-10-01 01:15:17 W. Europe Daylight Time,2022-10-01,01:15:17,200,1402701617867149313,lorenzo21341446,Lorenzo,...,NaN,NaN,NaN,NaN,NaN,"[{'screen_name': 'matteosalvinimi', 'name': 'M...",NaN,NaN,NaN,NaN
1061,18,1575987519774416896,1574307661138563072,2022-10-01 01:14:39 W. Europe Daylight Time,2022-10-01,01:14:39,200,1005382241818742784,parentesitonde,parentesi tonde,...,NaN,NaN,NaN,NaN,NaN,"[{'screen_name': 'lucatelese', 'name': 'Luca T...",NaN,NaN,NaN,NaN

Location: C:\Users\Giova\OneDrive\Desktop\UNIPI\MAGISTRALE\Social Network Analysis\meloni.csv
File Name: meloni.csv
Content:

,Unnamed: 0,id,conversation_id,created_at,date,time,timezone,user_id,username,name,...,geo,source,user_rt_id,user_rt,retweet_id,reply_to,retweet_date,translate,trans_src,trans_dest
0,3,1558603597511905280,1558371607973924864,2022-08-14 01:57:09 W. Europe Daylight Time,2022-08-14,01:57:09,200,588562092,madonnarossella,RossellaMadonna,...,NaN,NaN,NaN,NaN,NaN,"[{'screen_name': 'AlexCorsetti', 'name': 'Ales...",NaN,NaN,NaN,NaN
1,4,1558603517098606594,1555887161114873856,2022-08-14 01:56:50 W. Europe Daylight Time,2022-08-14,01:56:50,200,1445400656613883910,paolasarno67,Paola Sarno,...,NaN,NaN,NaN,NaN,NaN,"[{'screen_name': 'Andrea3000Re', 'name': 'Acqu...",NaN,NaN,NaN,NaN
2,7,1558603010326003714,1558371897469018112,2022-08-14 01:54:49 W. Europe Daylight Time,2022-08-14,01:54:49,200,968194818714361856,fulviocastella6,Cfulvio,...,NaN,NaN,NaN,NaN,NaN,"[{'screen_name': 'AugustoMinzolin', 'name': 'A...",NaN,NaN,NaN,NaN
3,10,1558602150074253313,1558601033101852672,2022-08-14 01:51:24 W. Europe Daylight Time,2022-08-14,01:51:24,200,505998407,stefanomentana,Stefano Mentana,...,NaN,NaN,NaN,NaN,NaN,"[{'screen_name': 'Yoda15271485', 'name': 'Yoda...",NaN,NaN,NaN,NaN
4,11,1558601893873696768,1558140371754012672,2022-08-14 01:50:23 W. Europe Daylight Time,2022-08-14,01:50:23,200,863439828133842944,linoemme11,Linoemme1,...,NaN,NaN,NaN,NaN,NaN,"[{'screen_name': 'VittorioSgarbi', 'name': 'Vi...",NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18919,19600,1575637454631350272,1575515664500113408,2022-09-30 02:03:37 W. Europe Daylight Time,2022-09-30,02:03:37,200,1433788752015544325,claudietto19,Claudio,...,NaN,NaN,NaN,NaN,NaN,"[{'screen_name': 'danse_lune', 'name': 'Sara',...",NaN,NaN,NaN,NaN
18920,19607,1575637169896448001,1575637169896448000,2022-09-30 02:02:29 W. Europe Daylight Time,2022-09-30,02:02:29,200,4432360889,lindaeciao,Linda,...,NaN,NaN,NaN,NaN,NaN,[],NaN,NaN,NaN,NaN
18921,19613,1575636822650015744,1575636822650015744,2022-09-30 02:01:07 W. Europe Daylight Time,2022-09-30,02:01:07,200,894925062268178433,antimopietro,Antimo Di Pietro,...,NaN,NaN,NaN,NaN,NaN,[],NaN,NaN,NaN,NaN
18922,19617,1575636763187367936,1575636763187367936,2022-09-30 02:00:52 W. Europe Daylight Time,2022-09-30,02:00:52,200,1472336698717655044,mgenerazion,✌️🐜my generaction👨🏻‍🚒🚒,...,NaN,NaN,NaN,NaN,NaN,[],NaN,NaN,NaN,NaN
18923,19623,1575636643263832064,1575636643263832064,2022-09-30 02:00:24 W. Europe Daylight Time,2022-09-30,02:00:24,200,808577548586250241,ratishtripathi,RatishTiwari,...,NaN,NaN,NaN,NaN,NaN,[],NaN,NaN,NaN,NaN

Location: C:\Users\Giova\OneDrive\Desktop\UNIPI\MAGISTRALE\Social Network Analysis\partitodemocratico.csv
File Name: partitodemocratico.csv
Content:

,Unnamed: 0,id,conversation_id,created_at,date,time,timezone,user_id,username,name,...,geo,source,user_rt_id,user_rt,retweet_id,reply_to,retweet_date,translate,trans_src,trans_dest
0,0,1558602849294188544,1558158936607522816,2022-08-14 01:54:11 W. Europe Daylight Time,2022-08-14,01:54:11,200,1420713180939046917,cacciamosche,cacciamosche,...,NaN,NaN,NaN,NaN,NaN,"[{'screen_name': 'PBerizzi', 'name': 'Paolo Be...",NaN,NaN,NaN,NaN
1,1,1558596462426177537,1558355214662615040,2022-08-14 01:28:48 W. Europe Daylight Time,2022-08-14,01:28:48,200,1402718910386950147,robertomaritan7,Roberto Maritan,...,NaN,NaN,NaN,NaN,NaN,"[{'screen_name': 'AMorzenti', 'name': 'Andrea ...",NaN,NaN,NaN,NaN
2,2,1558591184284565505,1558158580775370752,2022-08-14 01:07:50 W. Europe Daylight Time,2022-08-14,01:07:50,200,1254404383489634304,volpecala,Cala Di Volpe,...,NaN,NaN,NaN,NaN,NaN,"[{'screen_name': 'VivoLibera', 'name': 'Libera...",NaN,NaN,NaN,NaN
3,3,1558590765793775617,1558184058013769728,2022-08-14 01:06:10 W. Europe Daylight Time,2022-08-14,01:06:10,200,1548643277561290753,andreamezza63,andrea,...,NaN,NaN,NaN,NaN,NaN,"[{'screen_name': 'EnricoLetta', 'name': 'Enric...",NaN,NaN,NaN,NaN
4,4,1558587762407882753,1558587762407882752,2022-08-14 00:54:14 W. Europe Daylight Time,2022-08-14,00:54:14,200,2211965776,kscicciu,Antonello Cicciù,...,NaN,NaN,NaN,NaN,NaN,[],NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
985,149,1575727597400444928,1575727597400444928,2022-09-30 08:01:49 W. Europe Daylight Time,2022-09-30,08:01:49,200,422199745,ninocortesi,nino cortesi,...,NaN,NaN,NaN,NaN,NaN,[],NaN,NaN,NaN,NaN
986,150,1575718838481600512,1575718838481600512,2022-09-30 07:27:01 W. Europe Daylight Time,2022-09-30,07:27:01,200,231726084,zazoomblog,Zazoom Social News,...,NaN,NaN,NaN,NaN,NaN,[],NaN,NaN,NaN,NaN
987,151,1575708469834850304,1575589568430059520,2022-09-30 06:45:49 W. Europe Daylight Time,2022-09-30,06:45:49,200,1557993557016944640,giusouthern,GioSud 🌶,...,NaN,NaN,NaN,NaN,NaN,"[{'screen_name': 'liberalunicorno', 'name': 'L...",NaN,NaN,NaN,NaN
988,152,1575698911423234049,1567919053112483840,2022-09-30 06:07:50 W. Europe Daylight Time,2022-09-30,06:07:50,200,302738243,bellogiovanni,Giovanni Bello,...,NaN,NaN,NaN,NaN,NaN,"[{'screen_name': 'vdk_lmn', 'name': 'VdkParty'...",NaN,NaN,NaN,NaN
989,153,1575650884314431489,1575650884314431488,2022-09-30 02:56:59 W. Europe Daylight Time,2022-09-30,02:56:59,200,25508589,ilgiornale,ilGiornale,...,NaN,NaN,NaN,NaN,NaN,[],NaN,NaN,NaN,NaN

Location: C:\Users\Giova\OneDrive\Desktop\UNIPI\MAGISTRALE\Social Network Analysis\renzi.csv
File Name: renzi.csv
Content:

,Unnamed: 0,id,conversation_id,created_at,date,time,timezone,user_id,username,name,...,geo,source,user_rt_id,user_rt,retweet_id,reply_to,retweet_date,translate,trans_src,trans_dest
0,0,1557516958341505030,1557516958341505024,2022-08-11 01:59:14 W. Europe Daylight Time,2022-08-11,01:59:14,200,475234937,valy_s,Valeria S.,...,NaN,NaN,NaN,NaN,NaN,[],NaN,NaN,NaN,NaN
1,1,1557516395172306948,1557516395172306944,2022-08-11 01:57:00 W. Europe Daylight Time,2022-08-11,01:57:00,200,231726084,zazoomblog,Zazoom Social News,...,NaN,NaN,NaN,NaN,NaN,[],NaN,NaN,NaN,NaN
2,2,1557514664707346434,1557514664707346432,2022-08-11 01:50:07 W. Europe Daylight Time,2022-08-11,01:50:07,200,1431475300723040258,claudio_vacchio,claudio vacchio,...,NaN,NaN,NaN,NaN,NaN,[],NaN,NaN,NaN,NaN
3,3,1557513864597708801,1557513864597708800,2022-08-11 01:46:57 W. Europe Daylight Time,2022-08-11,01:46:57,200,1416214006742855680,caaarlotta_,c loves c,...,NaN,NaN,NaN,NaN,NaN,[],NaN,NaN,NaN,NaN
4,4,1557512703169777665,1557512703169777664,2022-08-11 01:42:20 W. Europe Daylight Time,2022-08-11,01:42:20,200,534499034,paninoelistino,Buddy Fox,...,NaN,NaN,NaN,NaN,NaN,[],NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
599,55,1569813302179414017,1569813302179414016,2022-09-14 00:20:31 W. Europe Daylight Time,2022-09-14,00:20:31,200,2858887492,raffanchio,raffaella nistri,...,NaN,NaN,NaN,NaN,NaN,[],NaN,NaN,NaN,NaN
600,56,1569813239856517120,1569681598924062720,2022-09-14 00:20:16 W. Europe Daylight Time,2022-09-14,00:20:16,200,1488871247228420097,giovann66413037,Giovanni,...,NaN,NaN,NaN,NaN,NaN,"[{'screen_name': 'GP_ArieteRosso', 'name': 'Gi...",NaN,NaN,NaN,NaN
601,57,1569813083836633096,1569802812409925632,2022-09-14 00:19:39 W. Europe Daylight Time,2022-09-14,00:19:39,200,990547134,daniloapriglian,Danilo Aprigliano 🇪🇺,...,NaN,NaN,NaN,NaN,NaN,"[{'screen_name': 'wirko94', 'name': 'Mirko', '...",NaN,NaN,NaN,NaN
602,58,1569812898108657666,1569812898108657664,2022-09-14 00:18:55 W. Europe Daylight Time,2022-09-14,00:18:55,200,1018148105517240320,nocoldizbot,RoboNocoldiz,...,NaN,NaN,NaN,NaN,NaN,[],NaN,NaN,NaN,NaN
603,59,1569812172091588609,1569687594245439488,2022-09-14 00:16:02 W. Europe Daylight Time,2022-09-14,00:16:02,200,1543661470428299264,osservatore1963,L'Osservatore,...,NaN,NaN,NaN,NaN,NaN,"[{'screen_name': 'CarloCalenda', 'name': 'Carl...",NaN,NaN,NaN,NaN

Location: C:\Users\Giova\OneDrive\Desktop\UNIPI\MAGISTRALE\Social Network Analysis\salvini.csv
File Name: salvini.csv
Content:

,Unnamed: 0,id,conversation_id,created_at,date,time,timezone,user_id,username,name,...,geo,source,user_rt_id,user_rt,retweet_id,reply_to,retweet_date,translate,trans_src,trans_dest
0,0,1571649557058002947,1571230188649828352,2022-09-19 01:57:08 W. Europe Daylight Time,2022-09-19,01:57:08,200,591459578,lalitapetila,lalita petila,...,NaN,NaN,NaN,NaN,NaN,"[{'screen_name': 'salvini_giacomo', 'name': 'G...",NaN,NaN,NaN,NaN
1,2,1571649010099683331,1571649010099683328,2022-09-19 01:54:58 W. Europe Daylight Time,2022-09-19,01:54:58,200,290093767,n36volpe1973,ARENA SALVATORE,...,NaN,NaN,NaN,NaN,NaN,[],NaN,NaN,NaN,NaN
2,3,1571648853878636544,1571648853878636544,2022-09-19 01:54:21 W. Europe Daylight Time,2022-09-19,01:54:21,200,1523370670218002432,berlus_killers_,MICHELE NISTA: VINCEREMO IL GENOCIDA BERLUS卐PU...,...,NaN,NaN,NaN,NaN,NaN,[],NaN,NaN,NaN,NaN
3,4,1571648580703887361,1571648580703887360,2022-09-19 01:53:16 W. Europe Daylight Time,2022-09-19,01:53:16,200,1523370670218002432,berlus_killers_,MICHELE NISTA: VINCEREMO IL GENOCIDA BERLUS卐PU...,...,NaN,NaN,NaN,NaN,NaN,[],NaN,NaN,NaN,NaN
4,5,1571647890547687426,1571565295700934656,2022-09-19 01:50:31 W. Europe Daylight Time,2022-09-19,01:50:31,200,2878609504,stercorariop,Stercorario Parlante ☮️💙💛☮️,...,NaN,NaN,NaN,NaN,NaN,"[{'screen_name': 'evamarghe', 'name': 'Eva Mar...",NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6867,3975,1575638691602890752,1575556804234412032,2022-09-30 02:08:32 W. Europe Daylight Time,2022-09-30,02:08:32,200,1242064698,nickwin59,Vajolet,...,NaN,NaN,NaN,NaN,NaN,"[{'screen_name': 'CarloCalenda', 'name': 'Carl...",NaN,NaN,NaN,NaN
6868,3976,1575638307110805504,1575638307110805504,2022-09-30 02:07:01 W. Europe Daylight Time,2022-09-30,02:07:01,200,231726084,zazoomblog,Zazoom Social News,...,NaN,NaN,NaN,NaN,NaN,[],NaN,NaN,NaN,NaN
6869,3977,1575637972216848384,1575608036705464320,2022-09-30 02:05:41 W. Europe Daylight Time,2022-09-30,02:05:41,200,1122301550616088578,trashometrus,Joanne Burrasca,...,NaN,NaN,NaN,NaN,NaN,"[{'screen_name': 'vincycernic2', 'name': 'LA S...",NaN,NaN,NaN,NaN
6870,3978,1575637770764423168,1575558755684478976,2022-09-30 02:04:53 W. Europe Daylight Time,2022-09-30,02:04:53,200,1471056672139395076,692troll,troll/692🇺🇦🇺🇦🇺🇦,...,NaN,NaN,NaN,NaN,NaN,"[{'screen_name': 'FrancoArlati', 'name': 'fran...",NaN,NaN,NaN,NaN
6871,3981,1575636747093913600,1575486343806799872,2022-09-30 02:00:49 W. Europe Daylight Time,2022-09-30,02:00:49,200,1045430343518617603,bruno76614337,Bruno,...,NaN,NaN,NaN,NaN,NaN,"[{'screen_name': 'sbonaccini', 'name': 'Stefan...",NaN,NaN,NaN,NaN

Location: C:\Users\Giova\OneDrive\Desktop\UNIPI\MAGISTRALE\Social Network Analysis\terzopolo.csv
File Name: terzopolo.csv
Content:

,Unnamed: 0,id,conversation_id,created_at,date,time,timezone,user_id,username,name,...,geo,source,user_rt_id,user_rt,retweet_id,reply_to,retweet_date,translate,trans_src,trans_dest
0,0,1557878520772173826,1557878520772173824,2022-08-12 01:55:57 W. Europe Daylight Time,2022-08-12,01:55:57,200,825866849250398209,agato_agato,Albertino,...,NaN,NaN,NaN,NaN,NaN,[],NaN,NaN,NaN,NaN
1,1,1557877397852225537,1557691666382856192,2022-08-12 01:51:30 W. Europe Daylight Time,2022-08-12,01:51:30,200,454282438,manliosai,MANLIO SAI,...,NaN,NaN,NaN,NaN,NaN,"[{'screen_name': 'forza_italia', 'name': 'Forz...",NaN,NaN,NaN,NaN
2,2,1557877041697103874,1557877041697103872,2022-08-12 01:50:05 W. Europe Daylight Time,2022-08-12,01:50:05,200,781468000088100864,jcrvo,Gianni Corvetta,...,NaN,NaN,NaN,NaN,NaN,[],NaN,NaN,NaN,NaN
3,3,1557876798167420929,1557876798167420928,2022-08-12 01:49:07 W. Europe Daylight Time,2022-08-12,01:49:07,200,422062831,giovannig1950,GIOVANNI 💯❤ 🇺🇦🇺🇳🏳️‍🌈,...,NaN,NaN,NaN,NaN,NaN,[],NaN,NaN,NaN,NaN
4,4,1557873466782765057,1557873466782765056,2022-08-12 01:35:53 W. Europe Daylight Time,2022-08-12,01:35:53,200,534499034,paninoelistino,Buddy Fox,...,NaN,NaN,NaN,NaN,NaN,[],NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1234,173,1575715406026637313,1575444864807981056,2022-09-30 07:13:22 W. Europe Daylight Time,2022-09-30,07:13:22,200,4785762898,stupormundi66,🇺🇦 Slava Ukraine 🇵🇸 Free Palestine,...,NaN,NaN,NaN,NaN,NaN,"[{'screen_name': 'pierofassino', 'name': 'Pier...",NaN,NaN,NaN,NaN
1235,174,1575714571590938625,1575714571590938624,2022-09-30 07:10:03 W. Europe Daylight Time,2022-09-30,07:10:03,200,1163437347372974088,marcocappa05,MK,...,NaN,NaN,NaN,NaN,NaN,[],NaN,NaN,NaN,NaN
1236,175,1575706427691536384,1575493493144707072,2022-09-30 06:37:42 W. Europe Daylight Time,2022-09-30,06:37:42,200,2333745212,mauriliovitto,Maurilio Vittoria,...,NaN,NaN,NaN,NaN,NaN,"[{'screen_name': 'VittorioXlater', 'name': 'Vi...",NaN,NaN,NaN,NaN
1237,176,1575702130450919424,1574178504522055680,2022-09-30 06:20:37 W. Europe Daylight Time,2022-09-30,06:20:37,200,427470597,angelodellosso,angelo dell'osso,...,NaN,NaN,NaN,NaN,NaN,"[{'screen_name': 'iammiammsimo', 'name': ""Non ...",NaN,NaN,NaN,NaN
1238,177,1575683752994680832,1575523973026258944,2022-09-30 05:07:36 W. Europe Daylight Time,2022-09-30,05:07:36,200,1549381362934743042,marghe1060,margherita,...,NaN,NaN,NaN,NaN,NaN,"[{'screen_name': 'Filippo_Rossi', 'name': 'Fil...",NaN,NaN,NaN,NaN

In [24]:
# Read each CSV file into DataFrame
# This creates a list of dataframes
df_list = (pd.read_csv(file) for file in csv_files)

# Concatenate all DataFrames
big_df   = pd.concat(df_list, ignore_index=True)

In [30]:
big_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 42190 entries, 0 to 42189
Data columns (total 38 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Unnamed: 0       42190 non-null  int64
 1   id               39757 non-null  float64
 2   conversation_id  39757 non-null  float64
 3   created_at       39757 non-null  object
 4   date             42190 non-null  object
 5   time             39757 non-null  object
 6   timezone         39757 non-null  float64
 7   user_id          42190 non-null  int64
 8   username         42190 non-null  object
 9   name             42188 non-null  object
 10  place            1 non-null      object
 11  tweet            42190 non-null  object
 12  language         39757 non-null  object
 13  mentions         42190 non-null  object
 14  urls             39757 non-null  object
 15  photos           39757 non-null  object
 16  replies_count    42190 non-null  int64
 17  retweets_count   42190 non-null  int64
 18  likes_count      42190 non-null  int64
 19  hashtags         42190 non-null  object
 20  cashtags         39757 non-null  object
 21  link             39757 non-null  object
 22  retweet          42190 non-null  bool
 23  quote_url        2740 non-null   object
 24  video            39757 non-null  float64
 25  thumbnail        3948 non-null   object
 26  near             0 non-null      float64
 27  geo              0 non-null      float64
 28  source           0 non-null      float64
 29  user_rt_id       0 non-null      float64
 30  user_rt          0 non-null      float64
 31  retweet_id       0 non-null      float64
 32  reply_to         42190 non-null  object
 33  retweet_date     0 non-null      float64
 34  translate        0 non-null      float64
 35  trans_src        0 non-null      float64
 36  trans_dest       0 non-null      float64
 37  Unnamed: 0.1     2433 non-null   float64
dtypes: bool(1), float64(15), int64(5), object(17)
memory usage: 12.0+ MB

In [40]:
df = big_df.drop(["geo", "retweet_id", "conversation_id", "time", "timezone","retweet_date", "id", "translate", "trans_src", "trans_dest", "near", "source", "user_rt_id","user_rt", "place", "thumbnail", "video", "language", "photos" , "created_at", "cashtags", "urls", "link", "quote_url"], axis=1)

In [41]:
df.shape

(42190, 14)

In [35]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 42190 entries, 0 to 42189
Data columns (total 16 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Unnamed: 0      42190 non-null  int64
 1   date            42190 non-null  object
 2   user_id         42190 non-null  int64
 3   username        42190 non-null  object
 4   name            42188 non-null  object
 5   tweet           42190 non-null  object
 6   mentions        42190 non-null  object
 7   replies_count   42190 non-null  int64
 8   retweets_count  42190 non-null  int64
 9   likes_count     42190 non-null  int64
 10  hashtags        42190 non-null  object
 11  retweet         42190 non-null  bool
 12  geo             0 non-null      float64
 13  retweet_id      0 non-null      float64
 14  reply_to        42190 non-null  object
 15  Unnamed: 0.1    2433 non-null   float64
dtypes: bool(1), float64(3), int64(5), object(7)
memory usage: 4.9+ MB

In [42]:
df.to_csv('df_tutti.csv')

In [43]:
by_week = pd.to_datetime(df['date']).dt.to_period('W').value_counts().sort_index()
by_week.index = pd.PeriodIndex(by_week.index)
df_week = by_week.rename_axis('Settimana').reset_index(name='tweet')
df_week

               Settimana  tweet
0  2022-08-08/2022-08-14    625
1  2022-08-15/2022-08-21   1204
2  2022-08-22/2022-08-28   1364
3  2022-08-29/2022-09-04   1583
4  2022-09-05/2022-09-11   1839
5  2022-09-12/2022-09-18   1819
6  2022-09-19/2022-09-25   2088
7  2022-09-26/2022-10-02  31668

In [20]:
!pip install plotly

Collecting plotly
  Downloading plotly-5.10.0-py2.py3-none-any.whl (15.2 MB)
Collecting tenacity>=6.2.0
  Downloading tenacity-8.1.0-py3-none-any.whl (23 kB)
Installing collected packages: tenacity, plotly
Successfully installed plotly-5.10.0 tenacity-8.1.0

In [44]:
import plotly.express as px
import plotly.graph_objs as go

fig = go.Figure(data=go.Scatter(x=df_week['Settimana'].astype(dtype=str), 
                        y=df_week['tweet'],
                        marker_color='indianred', text="counts"))
fig.update_layout({"title": 'Numero di tweet pubblicati quotidianamente durante le elezioni',
                   "xaxis": {"title":"Settimane"},
                   "yaxis": {"title":"Tweets Totali"},
                   "showlegend": False})
fig.show()

Amongst all types of interaction modes featured by the platform, the current study grounds on retweets, which
we understand as a baseline online relational mechanism that is particularly insightful when studying collective
political identities. Indeed, as pointed out in4
, while mentions and replies in Twitter do sustain direct interaction
and dialogue between users, retweets suggest a will to re-transmit contents produced by others. Tis, in turn,
provides a more clear-cut indication of commonality and shared points of reference. Moreover, extant research
suggests that retweets proxy the actual political alliances better than mentions and replies—as shown in32, where
authors conclude that the use of retweets was more relevant than that of mentions to grasp the bipartisan nature
of online debates in the run up of the 2010 US midterm elections.

In [46]:
df_terzopolo = pd.read_csv('terzopolo.csv')
by_week = pd.to_datetime(df_terzopolo['date']).dt.to_period('W').value_counts().sort_index()
by_week.index = pd.PeriodIndex(by_week.index)
df_terzopolo_week = by_week.rename_axis('Settimana').reset_index(name='tweet')
df_terzopolo_week

In [50]:
df_meloni = pd.read_csv('meloni28.csv')
by_week = pd.to_datetime(df_meloni['date']).dt.to_period('W').value_counts().sort_index()
by_week.index = pd.PeriodIndex(by_week.index)
df_meloni_week = by_week.rename_axis('Settimana').reset_index(name='tweet')
df_meloni_week

               Settimana  tweet
0  2022-08-08/2022-08-14    166
1  2022-08-15/2022-08-21    337
2  2022-08-22/2022-08-28    376
3  2022-08-29/2022-09-04    205
4  2022-09-05/2022-09-11    331
5  2022-09-12/2022-09-18    200
6  2022-09-19/2022-09-25    169
7  2022-09-26/2022-10-02  18486

In [51]:
df['reply_to'] = df['reply_to'].map(eval)
tupla = []

for index in range(0, len(df)):
    for dizionario in df['reply_to'][index]:
     #print("Mittente ",df_definitivo['user_id'][index], "id ", dizionario['id'])
      tupla.append((df['username'][index], df["user_id"][index], dizionario['screen_name'], dizionario["id"]))
        

df_reply = pd.DataFrame(tupla, columns = ["source", "id_source","target", "id_target"])

In [52]:
df['mentions'] = df['mentions'].map(eval)
tupla = []
for index in range(0, len(df)):
    for dizionario in df['mentions'][index]:
     #print("Mittente ",df_definitivo['user_id'][index], "id ", dizionario['id'])
      tupla.append((df['username'][index], df["user_id"][index], dizionario['screen_name'], dizionario["id"]))
        

df_mentions = pd.DataFrame(tupla, columns = ["source", "id_source","target", "id_target"])

In [53]:
df['retweet'] = df['retweet'].map(eval)
tupla = []
for index in range(0, len(df)):
    for dizionario in df['retweet'][index]:
     #print("Mittente ",df_definitivo['user_id'][index], "id ", dizionario['id'])
      tupla.append((df['username'][index], df["user_id"][index], dizionario['screen_name'], dizionario["id"]))
        

df_retweet = pd.DataFrame(tupla, columns = ["source", "id_source","target", "id_target"])

TypeError: eval() arg 1 must be a string, bytes or code object